### ISSUE TITLE
Correct license?

### ISSUE THREAD

**Issue by rjframe** [2night/arrogant#4]
Hi

How closely is this based on Modest? Just inspired by? If it's a port it's a derivative work and Modest is LGPL, so this wouldn't be able to be MIT.

**Comment by trikko** [comment]
Hello. What is your opinion @lexborisov ? I think my library is just a layer over modest, I don't modify your code. So I think license are not related, am I wrong?

**Comment by lexborisov** [comment]
Hi all, @rjframe , @trikko 
@trikko your code is MIT, my code is LGPL. I do not see contradictions.
